package org.integradorTC;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TOK_COMA = 35;
  public static final int TOK_MAYORIGUAL = 29;
  public static final int TOK_STRING = 7;
  public static final int TOK_TEXTO = 38;
  public static final int TOK_VOID = 8;
  public static final int TOK_FALSE = 14;
  public static final int TOK_ELSE = 11;
  public static final int TOK_ASIGNACION = 24;
  public static final int TOK_DIVIDE = 34;
  public static final int TOK_PARENTABRE = 18;
  public static final int TOK_IDCLASE = 40;
  public static final int TOK_CORCHIERRA = 21;
  public static final int TOK_CORCHABRE = 20;
  public static final int TOK_LLAVECIERRA = 17;
  public static final int TOK_COMILLAS = 22;
  public static final int TOK_MAS = 31;
  public static final int TOK_LLAVEABRE = 16;
  public static final int EOF = 0;
  public static final int TOK_IGUAL = 25;
  public static final int TOK_PARENTCIERRA = 19;
  public static final int error = 1;
  public static final int TOK_CLASS = 2;
  public static final int TOK_INT = 5;
  public static final int TOK_RETURN = 9;
  public static final int TOK_MENOS = 32;
  public static final int TOK_MENOR = 28;
  public static final int TOK_BOOL = 6;
  public static final int TOK_ANIMALPRINT = 15;
  public static final int TOK_MAYOR = 27;
  public static final int TOK_DISTINTO = 26;
  public static final int TOK_NUM = 37;
  public static final int TOK_MENORIGUAL = 30;
  public static final int TOK_MULTIPLICA = 33;
  public static final int TOK_PUNTO = 23;
  public static final int TOK_THIS = 4;
  public static final int TOK_FINAL = 36;
  public static final int TOK_WHILE = 12;
  public static final int TOK_IF = 10;
  public static final int TOK_NEW = 3;
  public static final int TOK_ID = 39;
  public static final int TOK_TRUE = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TOK_CLASS",
  "TOK_NEW",
  "TOK_THIS",
  "TOK_INT",
  "TOK_BOOL",
  "TOK_STRING",
  "TOK_VOID",
  "TOK_RETURN",
  "TOK_IF",
  "TOK_ELSE",
  "TOK_WHILE",
  "TOK_TRUE",
  "TOK_FALSE",
  "TOK_ANIMALPRINT",
  "TOK_LLAVEABRE",
  "TOK_LLAVECIERRA",
  "TOK_PARENTABRE",
  "TOK_PARENTCIERRA",
  "TOK_CORCHABRE",
  "TOK_CORCHIERRA",
  "TOK_COMILLAS",
  "TOK_PUNTO",
  "TOK_ASIGNACION",
  "TOK_IGUAL",
  "TOK_DISTINTO",
  "TOK_MAYOR",
  "TOK_MENOR",
  "TOK_MAYORIGUAL",
  "TOK_MENORIGUAL",
  "TOK_MAS",
  "TOK_MENOS",
  "TOK_MULTIPLICA",
  "TOK_DIVIDE",
  "TOK_COMA",
  "TOK_FINAL",
  "TOK_NUM",
  "TOK_TEXTO",
  "TOK_ID",
  "TOK_IDCLASE"
  };
}

